//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cliente_3.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/datos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet datos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/datos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> datosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertar(string nom, string ape, string fecha, int prom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> insertarAsync(string nom, string ape, string fecha, int prom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string actualizar(string nom, string ape, string fec, int prom, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> actualizarAsync(string nom, string ape, string fec, int prom, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminar(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> eliminarAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : cliente_3.ServiceReference2.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<cliente_3.ServiceReference2.WebService1Soap>, cliente_3.ServiceReference2.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet datos() {
            return base.Channel.datos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> datosAsync() {
            return base.Channel.datosAsync();
        }
        
        public string insertar(string nom, string ape, string fecha, int prom) {
            return base.Channel.insertar(nom, ape, fecha, prom);
        }
        
        public System.Threading.Tasks.Task<string> insertarAsync(string nom, string ape, string fecha, int prom) {
            return base.Channel.insertarAsync(nom, ape, fecha, prom);
        }
        
        public string actualizar(string nom, string ape, string fec, int prom, string id) {
            return base.Channel.actualizar(nom, ape, fec, prom, id);
        }
        
        public System.Threading.Tasks.Task<string> actualizarAsync(string nom, string ape, string fec, int prom, string id) {
            return base.Channel.actualizarAsync(nom, ape, fec, prom, id);
        }
        
        public string eliminar(string id) {
            return base.Channel.eliminar(id);
        }
        
        public System.Threading.Tasks.Task<string> eliminarAsync(string id) {
            return base.Channel.eliminarAsync(id);
        }
    }
}
